---
- name: Configure DNS servers
  hosts: all
  gather_facts: false
  collections:
    - brocade.fos
  vars:
    credential:
      fos_ip_addr: "{{ inventory_hostname }}"
      fos_user_name: "{{ ansible_user }}"
      fos_password: "{{ ansible_password }}"
      https: false
  tasks:
    - name: Set DNS servers
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          dns_servers:
            dns_server:
              - "w2k8s-20"
              - "W2k8s-16"
